title: AJRA
description: Web Developer & Data Analyst
url: "https://ajra.es" 
baseurl: "" 

permalink: /blog/:title/

author:
  name: AJRA
  email: ajra@ajra.es
  twitter: ajra_toni

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# SEO optimizations
twitter:
  username: ajra_toni
  card: summary_large_image

social:
  name: AJRA
  links:
    - https://twitter.com/ajra_toni
    - https://www.instagram.com/ajra_toni
    - https://github.com/ajratoni
    - https://www.linkedin.com/in/ajratoni

# GitHub Pages configuration
github: [metadata]
safe: true

